### PR TITLE
Initial settings needed for new treeview changes

### PR DESCRIPTION
**Pull request by ckipp01**
Start of changes necessary for https://github.com/scalameta/metals/pull/1677

### CODE REVIEW

**Comment by ckipp01** [comment]
@danilbykov is there any chance you'd be willing to take a look at this?

https://github.com/scalameta/coc-metals/blob/39ffb0e42b2a6fc5ab81967dcc30f0a9ff03342b/src/tvp/treeview.ts#L156

The `ev.root` here is undefined, and there is some logic here that I don't fully get:

https://github.com/scalameta/coc-metals/blob/39ffb0e42b2a6fc5ab81967dcc30f0a9ff03342b/src/tvp/treeview.ts#L146-L149

Would you have any time to take a peak at this and the new changes to the TVP [here](https://github.com/scalameta/metals/pull/1677). There really isn't much that has changed, but I'm assuming now that the compilations panel is just sending back `[]` we aren't fully accounting for it since it always had some Nodes in the past. Or would you be able to point me in the right direction?

Thanks!

**Comment by ckipp01** [comment]
Note that for the time being, I'm just turning off the compilations window. I've created an issue for this in hope that someone will pick it up, and if not I'll try to work on it when I have a bit more time.

**Comment by danilbykov** [comment]
Looking.

**Comment by ckipp01** [comment]
> Looking.

Thanks a bunch @danilbykov. I'm merging this now just because the new Metals is out, and without it the TVP panel will break. If you are able to get a fix and shoot in a pr adding the third window that'd be amazing 🙏 .

**Pull request merged**
