### PR TITLE
Delegate fetching and serverOptions to metals-languageclient

### PR DESCRIPTION
**Pull request by gabro**
Still draft since I haven't published 0.1.13 yet

### CODE REVIEW

**Comment by ckipp01** [comment]
It's so nice to see this stuff getting de-duplicated!

**Comment by gabro** [comment]
Ok, it's now ready to take for a spin

**Comment by ckipp01** [comment]
> Ok, it's now ready to take for a spin

Sounds good. I'm trying to track down what about the changed caused this, but it's unable to find `JAVA_HOME` now and upon opening a project, I'm getting the "Unable to find Java 8 or 11".

**Comment by gabro** [comment]
Ok, that’s something that shouldn’t happen 😅
By the way, what’s your workflow for testing locally?

**Comment by ckipp01** [comment]
> Cannot read property 'join' of undefined

Is what I'm seeing when looking at the err coming back from `getJavaHome`.

What I pretty much do is what is [listed here](https://github.com/scalameta/coc-metals/blob/master/CONTRIBUTING.md#cocnvim). I'll uninstall my coc-metals, and then build it locally, and just link it to where coc is pulling it from, then as I build or make changes, I just restart coc and it will pull in the newly built coc-metals.

**Comment by gabro** [comment]
Ah, I think I know what’s happening. coc.nvim returns undefined when there are no members of an array settings, whereas vscode returns an empty array. I’ll fix this upstream and publish a new version

**Comment by ckipp01** [comment]
Are you referring to the `workspace.getConfiguration("metals").get("javaHome")`? If so, for sure coc.nvim is returning an undefined here because I was just looking at that ha.

**Comment by ckipp01** [comment]
But that's not necessarily what is causing this right, since `getJavaHome` takes in a string or undefined.

**Comment by ckipp01** [comment]
On another note, I really need to figure out a way to automate some of this testing. I'll spend some time looking through other coc plugins, and see if I can see some examples. Last time I looked I didn't really see anything, but I think it's getting to be pretty important.

**Comment by gabro** [comment]
Ok, fixed now 👍 I've tested locally and it seems to work correctly

**Pull request merged**
